# Generated by Django 5.1.7 on 2025-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_adminuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='username',
            field=models.CharField(default='admin', max_length=150, unique=True),
        ),
    ]
