# Generated by Django 5.1.7 on 2025-03-22 14:38

import books.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_adminuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
                ('objects', books.models.AdminUserManager()),
            ],
        ),
    ]
